packages:
    - "cdk"
    - "synthetics"

catalog:
    "@guardian/eslint-config": ^16.0.0
    "@guardian/prettier": 11.0.0
    "@guardian/tsconfig": ^2.0.0
    typescript: 5.9.3
    eslint: ^9.39.2
    prettier: ^3.9.6
    ts-jest: ^29.4.12
    ts-node: ^10.9.2
    jest: ^30.4.2
    "@types/jest": ^30.0.0
    "@types/node": 26.1.1
