#!/usr/bin/env bash

set -e

CURRENT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ROOT_DIR="${CURRENT_DIR}/.."

EXPECTED_BUILT_DIRECTORIES=("assets" "aus" "ccpa" "lib" "tcfv2" "types")

get_absolute_path() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

BUILT_APP_DIR_PATH=$(get_absolute_path "${ROOT_DIR}/dist") # Get absolute path to dist folder

echo "Checking Dist folder for the different directories"
if test -d "${BUILT_APP_DIR_PATH}"; then # If the dist folder exists
  for dir in "${EXPECTED_BUILT_DIRECTORIES[@]}"; do # Loop through EXPECTED_BUILT_DIRECTORIES string array
    if [ ! -d "${BUILT_APP_DIR_PATH}/${dir}" ]; then # If the sub directory doesn't exist
    	echo "Error: Directory '${dir}' does not exist in ${BUILT_APP_DIR_PATH}"
    	exit 1
    fi
  done
  echo "The expected directories are in the dist directory"
  exit 0
else
  echo "Error: Can't find dist folder"
  exit 1
fi
